//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EforahWebapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestand
    {
        public int bestandId { get; set; }
        public string url { get; set; }
        public int verenigingId { get; set; }
        public string docType { get; set; }
        public string docNaam { get; set; }
        public int docGrootte { get; set; }
    
        public virtual Vereniging Vereniging { get; set; }
    }
}
