//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EforahWebapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lid()
        {
            this.Transactie = new HashSet<Transactie>();
        }
    
        public int lidId { get; set; }
        public int gebruikerId { get; set; }
        public int verenigingId { get; set; }
        public decimal saldo { get; set; }
        public string rol { get; set; }
    
        public virtual Gebruiker Gebruiker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactie> Transactie { get; set; }
        public virtual Vereniging Vereniging { get; set; }
    }
}
