//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EforahWebapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locatie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locatie()
        {
            this.Gebruiker = new HashSet<Gebruiker>();
            this.Vereniging = new HashSet<Vereniging>();
        }
    
        public int locatieId { get; set; }
        public string postcode { get; set; }
        public int huisnummer { get; set; }
        public string adres { get; set; }
        public string plaats { get; set; }
        public string UniqueAdres { get { return postcode + ": " + huisnummer; } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gebruiker> Gebruiker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vereniging> Vereniging { get; set; }
    }
}
