//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EforahWebapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mededeling
    {
        public int mededelingId { get; set; }
        public int verenigingId { get; set; }
        public System.DateTime plaatsingDatum { get; set; }
        public string titel { get; set; }
        public string mededeling1 { get; set; }
    
        public virtual Vereniging Vereniging { get; set; }
    }
}
