//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EforahWebapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactie
    {
        public int transactieId { get; set; }
        public int lidId { get; set; }
        public System.DateTime transactieDatum { get; set; }
        public decimal bedrag { get; set; }
    
        public virtual Lid Lid { get; set; }
    }
}
