//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EforahWebapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vereniging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vereniging()
        {
            this.Bestand = new HashSet<Bestand>();
            this.Lid = new HashSet<Lid>();
            this.Mededeling = new HashSet<Mededeling>();
        }
    
        public int verenigingId { get; set; }
        public int locatieId { get; set; }
        public string naam { get; set; }
        public string facebookAdminId { get; set; }
        public Nullable<long> facebookGroupId { get; set; }
        public string agendaLink { get; set; }
        public string telefoonnummer { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestand> Bestand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lid> Lid { get; set; }
        public virtual Locatie Locatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mededeling> Mededeling { get; set; }
    }
}
